---
title: "pm566_wk10_lab"
author: "Yiping Li" 
output: github_document
date: "`r Sys.Date()`" 
always_allow_html: true
---
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(parallel)
```

#problem 2: create a n x k matrix of Poisson 
```{r}
set.seed(1235)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}
f1<-fun1()
mean(f1)
```
```{r}
fun1alt <- function(n = 100, k = 4, lambda = 4) {
  x<-matrix(rpois(n*k, lambda),ncol=4)
}

# Benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)
```

```{r}
d <- matrix(1:16, ncol=4)
d[2,1]
d[2]
```
```{r}
diag(d)
d[c(1,6,11,16)]
cbind(1:4,1:4)
d[cbind(1:4,1:4)]
```

#problem3: find the column max (hint: Checkout the function max.col()).
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12), ncol=4)
M
# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
}
fun2(x=M)
fun2alt <- function(x) {
  # YOUR CODE HERE
   idx <- max.col( t(x))
   x[cbind(idx,1:4)]
}
fun2alt(x=M)
x <- matrix(rnorm(1e4), nrow=10)
# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)
```

#problem4: how PSOCK cluster example  
```{r}
library(parallel)

my_boot <- function(dat, stat, R, ncpus = 1L) 
{
  
  # Getting the random indices
  n <- nrow(dat)
  idx <- matrix(sample.int(n, n*R, TRUE), nrow=n, ncol=R)
 
  # Making the cluster using `ncpus`
  # STEP 1: GOES HERE
  
  cl <- makePSOCKcluster(4)  
  clusterSetRNGStream(cl, 123) # Equivalent to `set.seed(123)`
  # STEP 2: GOES HERE
  
  clusterExport(cl,c("stat","dat","idx"),envir=environment())
  
  # STEP 3: THIS FUNCTION NEEDS TO BE REPLACES WITH parLapply
  ans <- parLapply( cl,seq_len(R), function(i) {
    stat(dat[idx[,i], , drop=FALSE])
  })
  
  # Coercing the list into a matrix
  ans <- do.call(rbind, ans)
  
  # STEP 4: GOES HERE
  ans
  
}
```

```{r, Use the previous pseudocode, and make it work with parallel. Here is just an example for you to try}
# Bootstrap of an OLS
my_stat <- function(d) coef(lm(y ~ x, data=d))

# DATA SIM
set.seed(1)
n <- 500; R <- 1e4
x <- cbind(rnorm(n)); y <- x*5 + rnorm(n)

# Checking if we get something similar as lm
ans0 <- confint(lm(y~x))
ans1 <- my_boot(dat = data.frame(x, y), my_stat, R = R, ncpus = 2L)

#stopCluster(cl)
# You should get something like this
t(apply(ans1, 2, quantile, c(.025,.975)))
ans0
```

```{r, Check whether your version actually goes faster than the non-parallel version:}
system.time(my_boot(dat = data.frame(x, y), my_stat, R = 4000, ncpus = 1L))
system.time(my_boot(dat = data.frame(x, y), my_stat, R = 4000, ncpus = 2L))

```

